using AppForSEII2526.UIT.Shared;
using Microsoft.VisualStudio.TestPlatform.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Threading.Tasks;

namespace AppForSEII2526.UIT.UC_Plan
{
    public class UC_PlanClasses_UIT : UC_UIT
    {
        private SelectClassesForPlan_PO selectClassesForPlan_PO;
        private CreatePlan_PO createPlan_PO;
        private DetailPlan_PO detailPlan_PO;
        
        // Test data for classes (based on SeedData.cs)
        // IDs generated by database IDENTITY: Yoga=1, Spinning=2, CrossFit=3, Strech & Relax=4, Zumba=5, Pilates=6
        private const int classIdYoga = 1;
        private const string classNameYoga = "Yoga";
        private const string classTypeItemsYoga = "Yoga mat, Yoga block";
        private const string classDateYoga = "15/12/2025";
        private const string classTimeYoga = "18:00";
        private const string classPriceYoga = "11";
        
        private const int classIdPilates = 6;
        private const string classNamePilates = "Pilates";
        private const string classTypeItemsPilates = "Medicine Ball, Magic Ring";
        private const string classDatePilates = "20/12/2025";
        private const string classTimePilates = "15:30";
        private const string classPricePilates = "10";

        private const int classIdCrossFit = 3;
        private const string classNameCrossFit = "CrossFit";

        public UC_PlanClasses_UIT(ITestOutputHelper output) : base(output)
        {
            selectClassesForPlan_PO = new SelectClassesForPlan_PO(_driver, _output);
            createPlan_PO = new CreatePlan_PO(_driver, _output);
            detailPlan_PO = new DetailPlan_PO(_driver, _output);
        }

        private void Precondition_perform_login()
        {
            // Using a valid user from the database (dbo.AspNetUsers.data.sql)
            // Note: Update with actual credentials if needed
            Perform_login("alberto@uclm.es", "Pass123$");
        }

        private void InitialStepsForPlanClasses()
        {
            Precondition_perform_login();
            //we wait for the option of the menu to be visible
            selectClassesForPlan_PO.WaitForBeingVisible(By.Id("CreatePlan"));
            //we click on the menu
            _driver.FindElement(By.Id("CreatePlan")).Click();
        }

        // UC4-Esc2-1: No classes available for planning
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc2_1_NoClassesAvailable()
        {
            //Arrange
            InitialStepsForPlanClasses();
            
            //Act
            // Search with filters that won't return any results
            selectClassesForPlan_PO.SearchClasses("", "21/12/2025");

            //Assert
            Assert.True(selectClassesForPlan_PO.CheckMessageError("There are no classes available for the selected filters"));
        }

        // UC4-Esc3-1: Filter by Name - Y
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc3_1_FilterByName_Yoga()
        {
            //Arrange
            InitialStepsForPlanClasses();
            var expectedClasses = new List<string[]> { 
                new string[] { classNameYoga, classTypeItemsYoga, classDateYoga, classTimeYoga, classPriceYoga }
            };
            
            //Act
            selectClassesForPlan_PO.SearchClasses("Y", "");

            //Assert
            Assert.True(selectClassesForPlan_PO.CheckListOfClasses(expectedClasses));
        }

        // UC4-Esc3-2: Filter by Date - 20/12/2025 (Pilates)
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc3_2_FilterByDate_Pilates()
        {
            //Arrange
            InitialStepsForPlanClasses();
            var expectedClasses = new List<string[]> { 
                new string[] { classNamePilates, classTypeItemsPilates, classDatePilates, classTimePilates, classPricePilates }
            };
            
            //Act
            selectClassesForPlan_PO.SearchClasses("", "20/12/2025");

            //Assert
            Assert.True(selectClassesForPlan_PO.CheckListOfClasses(expectedClasses));
        }

        // UC4-Esc4-1: Date enrolment before today
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc4_1_DateBeforeToday()
        {
            //Arrange
            InitialStepsForPlanClasses();

            //Act
            selectClassesForPlan_PO.SearchClasses("", "10/12/2025");

            //Assert
            Assert.True(selectClassesForPlan_PO.CheckMessageError("The class date must be today or later"));
        }

        // UC4-Esc5-1: Modify plan cart - Add Yoga and Pilates, remove Yoga
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc5_1_ModifyPlanCart()
        {
            //Arrange
            InitialStepsForPlanClasses();
            
            //Act
            // Search and add Yoga and Pilates
            selectClassesForPlan_PO.SearchClasses("", "15/12/2025");
            selectClassesForPlan_PO.AddClassToPlanCart(classNameYoga);
            selectClassesForPlan_PO.AddClassToPlanCart(classNamePilates);
            
            // Remove Yoga
            selectClassesForPlan_PO.RemoveClassFromPlanCart(classIdYoga);

            //Assert
            // Verify that only Pilates remains in the cart
            // The Create Plan button should still be available since we have 1 class
            Assert.False(selectClassesForPlan_PO.CreatePlanNotAvailable());
        }

        // UC4-Esc6-1: Planning not available - Add and remove same class
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc6_1_PlanningNotAvailable()
        {
            //Arrange
            InitialStepsForPlanClasses();
            
            //Act
            // Search and add Yoga
            selectClassesForPlan_PO.SearchClasses("", "");
            selectClassesForPlan_PO.AddClassToPlanCart(classNameYoga);
            
            // Remove Yoga
            selectClassesForPlan_PO.RemoveClassFromPlanCart(classIdYoga);

            //Assert
            // Verify that the Create Plan button is disabled (not available)
            Assert.True(selectClassesForPlan_PO.CreatePlanNotAvailable());
        }

        // Helper method to navigate to CreatePlan page with a selected class
        private void InitialStepsForCreatePlan(string className)
        {
            InitialStepsForPlanClasses();
            
            // Search and add the specified class
            selectClassesForPlan_PO.SearchClasses(className, "");
            selectClassesForPlan_PO.AddClassToPlanCart(className);
            
            // Click on Create Plan button to navigate to CreatePlan page
            selectClassesForPlan_PO.WaitForBeingClickable(By.Id("createPlanButton"));
            _driver.FindElement(By.Id("createPlanButton")).Click();
        }

        // UC4-Esc7-1: Error in User Name - Required field
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc7_1_ErrorInUserNameRequired()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            
            //Act
            createPlan_PO.FillPlanForm("", "TestPlan", "8", "CreditCard");
            createPlan_PO.ClickSubmit();

            //Assert
            // Validation prevents dialog from opening
            Assert.True(createPlan_PO.CheckValidationSummaryError("The NameUser field is required"));
        }

        // UC4-Esc7-2: Error in User Name - User not registered
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc7_2_ErrorInUserNameNotRegistered()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            
            //Act
            createPlan_PO.FillPlanForm("juan", "TestPlan", "8", "CreditCard");
            createPlan_PO.ClickSubmit();
            createPlan_PO.ConfirmDialog(); // Confirm the dialog to send to server

            //Assert
            Assert.True(createPlan_PO.CheckMessageError("UserName is not registered"));
        }

        // UC4-Esc7-3: Error in User Name - Minimum length
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc7_3_ErrorInUserNameMinLength()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            
            //Act
            createPlan_PO.FillPlanForm("yo", "TestPlan", "8", "CreditCard");
            createPlan_PO.ClickSubmit();

            //Assert
            // Validation prevents dialog from opening
            Assert.True(createPlan_PO.CheckValidationSummaryError("The field NameUser must be a string with a minimum length of 3 and a maximum length of 50."));
        }

        // UC4-Esc7-4: Error in Plan Name - Required field
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc7_4_ErrorInPlanNameRequired()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "", "8", "CreditCard");
            createPlan_PO.ClickSubmit();

            //Assert
            // Validation prevents dialog from opening
            Assert.True(createPlan_PO.CheckValidationSummaryError("The Name field is required."));
        }

        // UC4-Esc7-5: Error in Plan Name - Maximum length
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc7_5_ErrorInPlanNameMaxLength()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "TestPlannificationOfTheYear2025/2026", "8", "CreditCard");
            createPlan_PO.ClickSubmit();

            //Assert
            // Validation prevents dialog from opening
            Assert.True(createPlan_PO.CheckValidationSummaryError("The field Name must be a string with a minimum length of 1 and a maximum length of 20."));
        }

        // UC4-Esc7-6: Error in Weeks - Must be between 1 and 52
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc7_6_ErrorInWeeksRange()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "TestPlan", "0", "CreditCard");
            createPlan_PO.ClickSubmit();

            //Assert
            // Validation prevents dialog from opening
            Assert.True(createPlan_PO.CheckValidationSummaryError("must be between 1 and 52"));
        }

        // UC4-Esc8-1: Not enough capacity - CrossFit has 0 capacity
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc8_1_NotEnoughCapacity()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameCrossFit);
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "TestPlannification", "3", "Paypal");
            createPlan_PO.ClickSubmit();
            createPlan_PO.ConfirmDialog(); // Confirm the dialog to send to server

            //Assert
            // Server returns error about capacity
            Assert.True(createPlan_PO.CheckMessageError("Minimum capacity is 1."));
        }

        // UC4-Esc1-1: Successful plan creation with Credit Card
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc1_1_CreatePlanWithCreditCard()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            string todayDate = DateTime.Now.ToString("dd/MM/yyyy");
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "TestPlan", "8", "CreditCard");
            createPlan_PO.ClickSubmit();
            createPlan_PO.ConfirmDialog(); // Confirm dialog to create plan
            Thread.Sleep(3000); // Wait for navigation

            //Assert
            // Verify we are on DetailPlan page with correct data
            Assert.True(detailPlan_PO.CheckPlanDetails(
                "Alberto Bueno Baquero",
                "TestPlan",
                "N/A",
                "8",
                "None",
                "11 €",
                todayDate
            ));
            
            // Verify enrolled class
            Assert.True(detailPlan_PO.CheckEnrolledClass(
                classNameYoga,
                classTypeItemsYoga,
                classPriceYoga + " €",
                classDateYoga,
                classTimeYoga
            ));
        }

        // UC4-Esc1-2: Successful plan creation with PayPal
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc1_2_CreatePlanWithPayPal()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            string todayDate = DateTime.Now.ToString("dd/MM/yyyy");
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "TestPlan2", "8", "Paypal");
            createPlan_PO.ClickSubmit();
            createPlan_PO.ConfirmDialog(); // Confirm dialog to create plan
            Thread.Sleep(3000); // Wait for navigation

            //Assert
            // Verify we are on DetailPlan page with correct data
            Assert.True(detailPlan_PO.CheckPlanDetails(
                "Alberto Bueno Baquero",
                "TestPlan2",
                "N/A",
                "8",
                "None",
                "11 €",
                todayDate
            ));
            
            // Verify enrolled class
            Assert.True(detailPlan_PO.CheckEnrolledClass(
                classNameYoga,
                classTypeItemsYoga,
                classPriceYoga + " €",
                classDateYoga,
                classTimeYoga
            ));
        }

        // UC4-Esc1-3: Successful plan creation with Bizum
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void UC4_Esc1_3_CreatePlanWithBizum()
        {
            //Arrange
            InitialStepsForCreatePlan(classNameYoga);
            string todayDate = DateTime.Now.ToString("dd/MM/yyyy");
            
            //Act
            createPlan_PO.FillPlanForm("alberto@uclm.es", "TestPlan3", "8", "Bizum");
            createPlan_PO.ClickSubmit();
            createPlan_PO.ConfirmDialog(); // Confirm dialog to create plan
            Thread.Sleep(3000); // Wait for navigation

            //Assert
            // Verify we are on DetailPlan page with correct data
            Assert.True(detailPlan_PO.CheckPlanDetails(
                "Alberto Bueno Baquero",
                "TestPlan3",
                "N/A",
                "8",
                "None",
                "11 €",
                todayDate
            ));
            
            // Verify enrolled class
            Assert.True(detailPlan_PO.CheckEnrolledClass(
                classNameYoga,
                classTypeItemsYoga,
                classPriceYoga + " €",
                classDateYoga,
                classTimeYoga
            ));
        }

        // Sprint 3 Exam: BF + AF1 + AF3
        [Fact]
        [Trait("LevelTesting", "Functional Testing")]
        public void Sprint3Exam_CreatePlan()
        {
            InitialStepsForPlanClasses();

            selectClassesForPlan_PO.SearchClasses("", "15/12/2025");
            selectClassesForPlan_PO.AddClassToPlanCart(classNamePilates);
            selectClassesForPlan_PO.SearchClasses("Yoga", "");



        }
    }
}